pre-commit:
  parallel: true
  commands:
    lint:
      run: pnpm run lint
    format:
      run: pnpm run format
    typecheck:
      run: pnpm run typecheck
commit-msg:
  commands:
    commitlint:
      run: pnpm exec commitlint --edit {1}
