
declare const obj: Record<
      "a-font-size-var___font_md_-screen_and__max_width__444px_" | 
      "a-flex-direction-column-screen_and__max_width__952px_" | 
      "a-gap-var___spacing_4xl_-screen_and__max_width__952px_" | 
      "a-text-align-center-screen_and__max_width__952px_" | 
      "a-justify-content-center-screen_and__max_width__952px_" | 
      "a-font-size-var___font_3xl_-screen_and__max_width__952px_" | 
      "hero-title" | 
      "hero" | 
      "hero-content" | 
      "hero-actions" | 
      "a-display-flex" | 
      "a-align-items-center" | 
      "a-justify-content-space_between" | 
      "a-padding-block-var___spacing_4xl_" | 
      "a-gap-var___spacing_6xl_" | 
      "a-min-height-500px" | 
      "a-flex-shrink-0" | 
      "a-font-size-var___font_3xl_" | 
      "a-font-weight-var___font_extrabold_" | 
      "a-line-height-1_2" | 
      "a-margin-bottom-var___spacing_xl_" | 
      "a-color-var___color_brand_" | 
      "a-font-weight-var___font_bold_" | 
      "a-position-relative" | 
      "a-font-size-var___font_md_" | 
      "a-color-var___text_muted_" | 
      "a-margin-bottom-var___spacing_4xl_" | 
      "a-gap-var___spacing_xl_" | 
      "a-margin-bottom-var___spacing_3xl_" | 
      "a-padding-0_75rem_1_5rem" | 
      "a-font-size-1rem" | 
      "a-font-weight-var___font_semibold_" | 
      "a-border-radius-999px" | 
      "a-text-decoration-none" | 
      "a-display-inline_block" | 
      "a-transition-background_color_0_2s_ease" | 
      "a-background-color-var___color_brand_" | 
      "a-color-white" | 
      "a-background-color-color_mix_in_srgb__var___color_brand__80___black_-hover" | 
      "a-background-color-_f0f0f0" | 
      "a-color-_333" | 
      "a-background-color-_e0e0e0-hover" | 
      "a-min-height-400px" | 
      "a-width-100_" | 
      "a-flex-direction-column" | 
      "a-color-var___text_primary_" | 
      "a-font-family-var___font_family_sans_" | 
      "a-border-bottom-1px_solid_var___text_muted_" | 
      "a-padding-var___spacing_md_" | 
      "a-cursor-default" | 
      "a-outline-none" | 
      "a-transition-color_200ms" | 
      "a---border-color-transparent" | 
      "a-border-bottom-3px_solid_var___border_color_" | 
      "a-forced-color-adjust-none" | 
      "a-font-size-var___font_sm_" | 
      "a-cursor-pointer" | 
      "a---border-color-var___color_brand_" | 
      "a-margin-top-var___spacing_sm_" | 
      "a-border-radius-var___radii_sm_" | 
      "a-background-var___surface_primary_" | 
      "a-padding-block-var___spacing_3xl_" | 
      "a-font-weight-var___font_weight_bold_" | 
      "a-font-size-var___font_lg_" | 
      "a-content-_Beta_-_after" | 
      "a-color-var___text_primary_-_after" | 
      "a-font-size-var___font_xs_-_after" | 
      "a-background-color-var___surface_critical_-_after" | 
      "a-position-absolute-_after" | 
      "a-border-radius-var___radii_sm_-_after" | 
      "a-padding-inline-var___spacing_sm_-_after" | 
      "a-padding-block-var___spacing_xs_-_after" | 
      "a-top-calc__1___var___spacing_lg__-_after" | 
      "a-right-0-_after" | 
      "a-gap-1rem" | 
      "a-color-inherit" | 
      "a-text-decoration-underline-hover" | 
      "a-all-unset" | 
      "a-color-var___text_warning_" | 
      "a-display-grid" | 
      "a-grid-template-columns-repeat_auto_fit__minmax_250px__1fr__" | 
      "a-gap-1_5rem" | 
      "a-background-color-var___surface_card_" | 
      "a-border-radius-0_75rem" | 
      "a-padding-1_5rem" | 
      "a-box-shadow-0_0_0_1px_rgba_255__255__255__0_05_" | 
      "a-transition-transform_0_2s_ease" | 
      "a-transform-translateY__4px_-hover" | 
      "a-font-size-2rem" | 
      "a-background-color-var___surface_primary_" | 
      "a-width-3rem" | 
      "a-height-3rem" | 
      "a-border-radius-0_5rem" | 
      "a-justify-content-center" | 
      "a-margin-bottom-1rem" | 
      "a-font-size-1_2rem" | 
      "a-font-weight-600" | 
      "a-margin-bottom-0_5rem" | 
      "a-font-size-0_95rem" | 
      "a-line-height-1_5" | 
      "features-container" | 
      "feature-card" | 
      "feature-icon" | 
      "feature-title" | 
      "feature-description" | 
      "hero-brand" | 
      "hero-subtitle" | 
      "button" | 
      "button--primary" | 
      "button--secondary" | 
      "hero-codeblock" | 
      "react-aria-Tabs" | 
      "react-aria-TabList" | 
      "react-aria-Tab" | 
      "react-aria-Tab-selected" | 
      "react-aria-TabPanel" | 
      "header" | 
      "logo" | 
      "nav" | 
      "nav-link" | 
      "toggle" | 
      "toggle--icon-light"
,
  string[]
>;
export default obj;