declare const obj: Record<
  | "hero-title"
  | "hero"
  | "hero-content"
  | "hero-actions"
  | "hero-brand"
  | "hero-subtitle"
  | "button"
  | "button--primary"
  | "button--secondary"
  | "hero-codeblock"
  | "react-aria-Tabs"
  | "react-aria-TabList"
  | "react-aria-Tab"
  | "react-aria-Tab-selected"
  | "react-aria-TabPanel"
  | "header"
  | "logo"
  | "nav"
  | "nav-link"
  | "toggle"
  | "toggle--icon-light"
  | "features-container"
  | "feature-card"
  | "feature-icon"
  | "feature-title"
  | "feature-description",
  string[]
>;
export default obj;
