export const abbreviations: Record<string, string> = {
  // Layout
  "aspect-ratio": "asp",
  "box-sizing": "box",
  display: "d",
  float: "fl",
  clear: "cl",
  "object-fit": "of",
  "object-position": "op",
  overflow: "ov",
  "overflow-x": "ov-x",
  "overflow-y": "ov-y",
  "overscroll-behavior": "ovs",
  "overscroll-behavior-x": "ovs-x",
  "overscroll-behavior-y": "ovs-y",
  position: "pos",
  top: "t",
  right: "r",
  bottom: "b",
  left: "l",
  inset: "ins",
  visibility: "vis",
  "z-index": "z",

  // Flexbox & Grid
  "flex-basis": "basis",
  "flex-direction": "fld", // flex-direction
  "flex-wrap": "flw", // flex-wrap
  flex: "fx", // distinct from float 'fl'
  "flex-grow": "grow",
  "flex-shrink": "shrink",
  order: "ord",
  "grid-template-columns": "gtc",
  "grid-column": "gc",
  "grid-column-start": "gcs",
  "grid-column-end": "gce",
  "grid-template-rows": "gtr",
  "grid-row": "gr",
  "grid-row-start": "grs",
  "grid-row-end": "gre",
  "grid-auto-flow": "gaf",
  "grid-auto-columns": "gac",
  "grid-auto-rows": "gar",
  gap: "g",
  "column-gap": "gx",
  "row-gap": "gy",
  "justify-content": "jc",
  "justify-items": "ji",
  "justify-self": "js",
  "align-content": "ac",
  "align-items": "ai",
  "align-self": "as",
  "place-content": "pc",
  "place-items": "pi",
  "place-self": "ps",

  // Spacing
  padding: "p",
  "padding-top": "pt",
  "padding-right": "pr",
  "padding-bottom": "pb",
  "padding-left": "pl",
  "padding-inline": "px",
  "padding-block": "py",
  margin: "m",
  "margin-top": "mt",
  "margin-right": "mr",
  "margin-bottom": "mb",
  "margin-left": "ml",
  "margin-inline": "mx",
  "margin-block": "my",

  // Sizing
  width: "w",
  "min-width": "min-w",
  "max-width": "max-w",
  height: "h",
  "min-height": "min-h",
  "max-height": "max-h",

  // Typography
  "font-family": "font",
  "font-size": "fs",
  "font-smoothing": "f-sm",
  "font-style": "fst",
  "font-weight": "fw",
  "font-variant-numeric": "fvn",
  "letter-spacing": "ls",
  "line-height": "lh",
  "list-style-type": "lst",
  "list-style-position": "lsp",
  "text-align": "ta",
  color: "txc", // text-color
  "text-decoration": "td",
  "text-decoration-color": "tdc",
  "text-decoration-style": "tds",
  "text-decoration-thickness": "tdt",
  "text-underline-offset": "tuo",
  "text-transform": "tt",
  "text-overflow": "tov",
  indent: "indent",
  "vertical-align": "va",
  "white-space": "ws",
  "word-break": "wb",
  content: "cnt",

  // Backgrounds
  "background-attachment": "bga",
  "background-clip": "bg-clip",
  "background-color": "bgc",
  "background-origin": "bgo",
  "background-position": "bgp",
  "background-repeat": "bgr",
  "background-size": "bgs",
  "background-image": "bgi",

  // Borders
  "border-radius": "br",
  "border-top-left-radius": "br-tl",
  "border-top-right-radius": "br-tr",
  "border-bottom-right-radius": "br-br",
  "border-bottom-left-radius": "br-bl",
  "border-width": "bw",
  "border-top-width": "btw",
  "border-right-width": "brw",
  "border-bottom-width": "bbw",
  "border-left-width": "blw",
  "border-color": "bdc", // border-color
  "border-style": "bds",
  "divide-width": "dw",
  "divide-color": "dc",
  "divide-style": "ds",
  "outline-width": "ow",
  "outline-color": "oc",
  "outline-style": "os",
  "outline-offset": "oo",
  "ring-width": "ring-w",
  "ring-color": "ring-c",
  "ring-offset-width": "ring-ow",
  "ring-offset-color": "ring-oc",

  // Effects & Filters
  "box-shadow": "shadow",
  opacity: "opc", // distinct from object-position 'op'
  "mix-blend-mode": "m-bl",
  "background-blend-mode": "bg-bl",
  filter: "flt", // distinct from float 'fl'
  blur: "blur",
  brightness: "bright",
  contrast: "contrast",
  "drop-shadow": "d-shdw",
  grayscale: "grscl",
  "hue-rotate": "hue-rt",
  invert: "invrt",
  saturate: "satur",
  sepia: "sepia",

  // Transitions & Animation
  "transition-property": "tnp",
  "transition-duration": "tnd",
  "transition-timing-function": "tnt",
  "transition-delay": "tndl",
  animation: "anim",

  // Transforms
  transform: "tf",
  scale: "sc",
  rotate: "rot",
  translate: "tr",
  skew: "sk",
  "transform-origin": "tfo",

  // Interactivity
  "accent-color": "acc",
  appearance: "apr",
  cursor: "cur",
  "caret-color": "caret-c",
  "pointer-events": "pe",
  resize: "resize",
  "scroll-behavior": "sb",
  "scroll-margin": "sm",
  "scroll-padding": "sp",
  "scroll-snap-align": "sa",
  "scroll-snap-stop": "ss",
  "scroll-snap-type": "st",
  "touch-action": "touch",
  "user-select": "select",

  // SVG
  fill: "fill",
  stroke: "stroke",
  "stroke-width": "sw",

  // Common Values
  center: "c",
  start: "s",
  end: "e",
  between: "btw",
  around: "arnd",
  evenly: "evn",
  stretch: "str",
};

export const atRuleAbbreviations: Record<string, string> = {
  media: "m",
  container: "c",
};
export const pseudoAbbreviations: Record<string, string> = {
  // Common User Action States
  ":hover": "hvr",
  ":active": "act",
  ":focus": "fcs",
  ":focus-within": "fcw",
  ":focus-visible": "fcv",
  ":visited": "vst",
  ":target": "tgt",

  // Input & Form States
  ":checked": "chk",
  ":disabled": "dis",
  ":enabled": "en",
  ":required": "req",
  ":optional": "opt",
  ":valid": "val",
  ":invalid": "inv",
  ":read-only": "ro",
  ":read-write": "rw",
  ":placeholder-shown": "ph-show",
  ":in-range": "in-range",
  ":out-of-range": "out-range",

  // Structural Pseudo-Classes
  ":first-child": "first",
  ":last-child": "last",
  ":only-child": "only",
  ":nth-child": "nth", // For dynamic classes like nth-of-3
  ":first-of-type": "first-of",
  ":last-of-type": "last-of",
  ":only-of-type": "only-of",
  ":nth-of-type": "nth-of",
  ":empty": "empty",

  // Pseudo-Elements (treated as prefixes)
  "::before": "bef",
  "::after": "aft",
  "::placeholder": "ph",
  "::marker": "marker",
  "::selection": "sel",
  "::first-line": "f-line",
  "::first-letter": "f-let",
};
